CREATE TABLE IPS_PEDIDO_PRODUCTO
(
  PEDIDO_ID VARCHAR2(36) NOT NULL 
, PRODUCT_ID VARCHAR2(36)
, UNIDADES INT NOT NULL 
, PRICE FLOAT NOT NULL 
, DESCUENTO INT
, CONSTRAINT IPS_PEDIDO_PRODUCTO_PK1 PRIMARY KEY 
  (
    PEDIDO_ID
    ,PRODUCT_ID
  )
  ENABLE  
, CONSTRAINT IPS_PEDIDO_PRODUCTO_FK1 FOREIGN KEY (PEDIDO_ID)
	  REFERENCES IPS_PEDIDO (PEDIDO_ID) ENABLE
, CONSTRAINT IPS_PEDIDO_PRODUCTO_FK2 FOREIGN KEY (PRODUCT_ID)
	  REFERENCES IPS_PRODUCTOS (PRODUCT_ID) ENABLE
, CONSTRAINT IPS_PEDIDOS_PROVEEDOR_CK1 CHECK
  (
    UNIDADES>0
  )
)
