CREATE TABLE IPS_TRANSPORTISTAS
( 
  ID VARCHAR2(36) NOT NULL
, ID_EMPLEADO VARCHAR(36) NOT NULL
, CONSTRAINT IPS_TRANSPROTISTA_PK PRIMARY KEY 
  (
    ID
  ) 
  ENABLE
, CONSTRAINT IPS_TRANSPORTISTAS_FK1 FOREIGN KEY (ID_EMPLEADO)
	 REFERENCES IPS_EMPLEADOS (ID) 
ENABLE
)