CREATE TABLE ips_vendedores
( 
  id VARCHAR2(20) NOT NULL
, ID_EMPLEADO VARCHAR(20) NOT NULL
, CONSTRAINT ips_vendedores_PK PRIMARY KEY 
  (
    id
  ) 
  ENABLE
, CONSTRAINT ips_vendedores_FK1 FOREIGN KEY (ID_EMPLEADO)
	 REFERENCES IPS_EMPLEADOS (ID) 
ENABLE
)