insert into ips_productos(product_id,name,type,price) values ('001','mesa alta','mesa',10.00)
insert into ips_productos(product_id,name,type,price) values ('002','mesa baja','mesa',20.00)
insert into ips_productos(product_id,name,type,price) values ('003','silla alta','para sentarse',7.50)
insert into ips_productos(product_id,name,type,price) values ('004','silla baja','para sentarse',8.99)
insert into ips_productos(product_id,name,type,price) values ('005','lampara de techo','iluminacion',34.89)
insert into ips_productos(product_id,name,type,price) values ('006','lampara de escritorio','iluminacion',22.55)
insert into ips_productos(product_id,name,type,price) values ('007','mesita de noche','mesa',11.99)
insert into ips_productos(product_id,name,type,price) values ('008','mesa de comedor','mesa',34.99)
insert into ips_productos(product_id,name,type,price) values ('009','sofa 3 plazas','para sentarse',50.00)
insert into ips_productos(product_id,name,type,price) values ('010','sillon','para sentarse',41.99)