CREATE TABLE IPS_PRESUPUESTOS_PRODUCTOS
(
  PRESUPUESTO_ID VARCHAR2(4) NOT NULL 
, PRODUCT_ID VARCHAR2(4) NOT NULL
, UNIDADES NUMBER NOT NULL
, CONSTRAINT IPS_PRESUPUESTOS_PRODUCTOS_PK PRIMARY KEY 
  (
    PRESUPUESTO_ID 
  , PRODUCT_ID 
  )
  ENABLE 
, CONSTRAINT IPS_PRESUPUESTOS_PRODUCTOS_FK1 FOREIGN KEY (PRESUPUESTO_ID)
	 REFERENCES IPS_PRESUPUESTOS (PRESUPUESTO_ID) 
ENABLE
, CONSTRAINT IPS_PRESUPUESTOS_PRODUCTOS_FK2 FOREIGN KEY (PRODUCT_ID)
	  REFERENCES IPS_PRODUCTOS (PRODUCT_ID)
ENABLE
, CONSTRAINT IPS_PRESUPUESTOS_PRO_CHK3 CHECK 
  (
    UNIDADES>=0
  ) 
ENABLE
)