CREATE TABLE IPS_PRESUPUESTOS_PRODUCTOS
(
  PRESUPUESTO_ID VARCHAR2(4) NOT NULL 
, PRODUCT_ID VARCHAR2(4) NOT NULL
, RECOGER NUMBER NOT NULL
, MONTAR NUMBER NOT NULL
, UNIDADES NUMBER NOT NULL
, CONSTRAINT IPS_PRESUPUESTOS_PRODUCTOS_PK PRIMARY KEY 
  (
    PRESUPUESTO_ID 
  , PRODUCT_ID 
  )
  ENABLE 
, CONSTRAINT IPS_PRESUPUESTOS_PRODUCTOS_FK1 FOREIGN KEY (PRESUPUESTO_ID)
	 REFERENCES IPS_PRESUPUESTOS (PRESUPUESTO_ID) 
ENABLE
, CONSTRAINT IPS_PRESUPUESTOS_PRODUCTOS_FK2 FOREIGN KEY (PRODUCT_ID)
	  REFERENCES IPS_PRODUCTOS (PRODUCT_ID)
ENABLE
, CONSTRAINT IPS_PRESUPUESTOS_PRO_CHK1 CHECK 
  (
    RECOGER=1 OR RECOGER=0
  ) 
  ENABLE
, CONSTRAINT IPS_PRESUPUESTOS_PRO_CHK2 CHECK 
  (
    MONTAR=1 OR MONTAR=0
  ) 
ENABLE
, CONSTRAINT IPS_PRESUPUESTOS_PRO_CHK3 CHECK 
  (
    UNIDADES>=0
  ) 
ENABLE
)