CREATE TABLE IPS_ALMACEN_PRODUCTO
(
  PRODUCT_ID VARCHAR2(4) NOT NULL 
, UNIDADES NUMBER NOT NULL 
, CONSTRAINT IPS_ALMACEN_PRODUCTO_PK PRIMARY KEY 
  (
    PRODUCT_ID 
  )
  ENABLE 
, CONSTRAINT IPS_ALMACEN_PRODUCTO_FK FOREIGN KEY (PRODUCT_ID)
	  REFERENCES IPS_PRODUCTOS (PRODUCT_ID) ENABLE
, CONSTRAINT IPS_ALMACEN_PRODUCTO_CHK CHECK 
  (
    UNIDADES>=0
  ) 
ENABLE
)